server:
  port: 8080
spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    open-in-view: false
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog.yaml
    default-schema: public
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: client-jopa@gmail.com
#            client-secret: google-client-secret